# Generated by Django 4.0 on 2022-01-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='text',
            new_name='title',
        ),
    ]
